# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aebdf31410650db019426761728544da02cbb8c3e691197f26980e3eba541a4c6ee3bb70ddcda3406ad06eb256a69c8829f237d935ecdc5138691c8580aa009

test:
  secret_key_base: 1277c309be1aca2a71132e0defd1210ddb7e161f323cfdce41315d3dc5dda7064285b25db24e9a6ade263d9bd05137533d93a692c04ce6f296cb228e9426faba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
